### PR TITLE
Updated demos

### PR DESCRIPTION
**Pull request by dsyme**
I updated the demos, please take a look

### CODE REVIEW

**Comment by dsyme** [comment]
Whoops, I need to adjust this for the recent changes around connection strings etc.

**Comment by dsyme** [comment]
OK, this is ready to go.  @palladin - please check the code in sample number 2.

**Comment by palladin** [comment]
The sample code looks good to me.

**Comment by drcrook1** [comment]
I am getting no workers available in my cluster.
mbraceactive
mbracenoworkers

**Comment by drcrook1** [comment]
Also note that deleting a cluster does not remove all resources associated with it.  I have created and deleted 2 clusters so far and each has left artifacts in my portal.

**Comment by isaacabraham** [comment]
@drcrook1 resolving this through uservoice.

**Pull request merged**
