### PR TITLE
update samples to use CreateProcess and add CloudStream over CloudFiles

### PR DESCRIPTION
**Pull request by dsyme**
This updates the samples to use CreateProcess, and adds a sample of using CloudStream over CloudFiles

### CODE REVIEW

**Comment by dsyme** [comment]
I've used "Process" as the systematic suffix for the things returned by CreateProcess. This is a bit heavy and it may be better to just use "P"

Compare this:

```
let sumOfLengthsOfLinesProcess = 
    namedCloudFiles
    |> CloudStream.ofCloudFiles CloudFile.ReadAllLines
    |> CloudStream.map (fun lines -> lines |> Array.sumBy (fun line -> line.Length))
    |> CloudStream.toArray
    |> cluster.CreateProcess

// Check progress
sumOfLengthsOfLinesProcess.ShowInfo()

// Get the result
let sumOfLengthsOfLines = sumOfLengthsOfLinesProcess.AwaitResult()
```

with this:

```
let sumOfLengthsOfLinesP = 
    namedCloudFiles
    |> CloudStream.ofCloudFiles CloudFile.ReadAllLines
    |> CloudStream.map (fun lines -> lines |> Array.sumBy (fun line -> line.Length))
    |> CloudStream.toArray
    |> cluster.CreateProcess 

// Check progress
sumOfLengthsOfLinesP.ShowInfo()

// Get the result
let sumOfLengthsOfLines = sumOfLengthsOfLinesP.AwaitResult()
```

**Comment by dsyme** [comment]
@eiriktsarpalis  @palladin @isaacabraham - we should standardize on one of the two above.  I do like using CreateProcess as it gives an immediate handle on job control, which is kind of crucial in practice.

**Comment by palladin** [comment]
I agree, as a person who has done a lot of MBrace cloud {} programming,
CreateProcess is the default for me.

**Comment by eiriktsarpalis** [comment]
I like using the `Proc` suffix, personally.

**Comment by isaacabraham** [comment]
I personally avoid any type of naming that includes the type in it - feels like a throwback to the old hungarian notation days. So I would have nothing at all :-) In the samples thus far I just used the word "job" since process is a reserved word.

**Comment by dsyme** [comment]
@isaacabraham  - I agree, but we need a naming pattern for this recurring pattern (which I think we need to use consistently instead of the beguiling-but-blocking "Run" :) ):

```
let resultJob = ... |> cluster.CreateProcess 

// Check progress
resultJob.ShowInfo()

// Get the result
let result = resultJob.AwaitResult()
```

**Comment by isaacabraham** [comment]
Yep - so i'd be happy using postfixing with Process or P (or anything) - some consistency is better than nothing for sure, even if it has to change later.

**Pull request merged**
