### PR TITLE
Put a single config instance into credentials.fsx.

### PR DESCRIPTION
**Pull request by isaacabraham**

### CODE REVIEW

**Comment by isaacabraham** [comment]
@dsyme @eiriktsarpalis review please :-)

**Comment by dsyme** [comment]
LGTM

**Comment by isaacabraham** [comment]
I'd never seen this LGTM thing until recently. Seems like the whole F# team have adopted this recently when reviewing PRs :-)

**Comment by dsyme** [comment]
BTW at the moment it's not possible to run 

```
let cluster = Runtime.GetHandle(config)
```

twice in a single F# Interactive session - it complains with the error below. That's a shame.  I'll file an MBrace bug on this.

``
System.InvalidOperationException: A a cache store has already been declared under 'DefaultCacheContext'.
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at MBrace.Runtime.Store.FileStoreCache.RegisterLocalCacheStore(ICloudFileStore localCacheStore, FSharpOption`1 cacheContext, FSharpOption`1 cacheBehavior) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 116
   at MBrace.Runtime.Store.FileStoreCache.RegisterLocalFileSystemCache(FSharpOption`1 cacheContext, FSharpOption`1 cacheBehavior) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 126
   at MBrace.Azure.Client.StoreClient..ctor(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\StoreClient.fs:line 200
   at MBrace.Azure.Client.StoreClient.Create(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\StoreClient.fs:line 237
   at MBrace.Azure.Client.Runtime..ctor(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 27
   at MBrace.Azure.Client.Runtime.GetHandle(Configuration config, FSharpOption`1 waitWorkerCount) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 175
   at <StartupCode$FSI_0009>.$FSI_0009.main@() in C:\GitHub\dsyme\mbrace-on-brisk-starter\src\Demos\7-cloud-files.fsx:line 24

``

**Pull request merged**
