### PR TITLE
Some further fixes to samples

### PR DESCRIPTION
**Pull request by dsyme**
some things were missing from fsproj

### CODE REVIEW

**Comment by isaacabraham** [comment]
Do you think it's worth bringing back a "simplified" single threaded / parallel / distributed one like we had originally which just illustrated the fact that work was being distributed rather than one that compares performance?

**Comment by dsyme** [comment]
The simple single-threaded version does come first, it's "localMachineSingleThreadedAnswer"

The simple distributed version is "clusterAnswerMultiWorkerSingleThreaded".

The missing one is the local multi-threaded version.  One problem is that on most people's personal dev machine, the local-parallel one is actually quite fast.  My laptop (which is pretty fast) is actually faster than a 3 machine "large instance" cluster, at least when the cluster is used in single-threaded mode. Mind you, my local machine tends to run out of memory more easily.

So it's hard to tell.  I'd actually like advice about at what stage we would introduce people to multi-core programming on the cluster - or is it possible with MBrace.Azure to arrange multiple workers on each node, and then use that to drive work through the multiple cores. 

So yes, it's possible we want a simpler sample at position 3

**Comment by eiriktsarpalis** [comment]
Every node will dequeue multiple jobs concurrently up to a specified number. So theoretically speaking the multicore capacity of workers should be utilized even without doing so explicitly, albeit in a naive way. 

However, improperly managing the granularity of created tasks results in communication overhead that can kill performance. I would suspect that the reason why the 'MultiWorker' examples are in fact slower than in-memory execution relates to the communication/serialization overhead which is significant when compared to the actual computation performed. I think performance can be somewhat improved by eliminating the input array and representing the input numbers by their upper bound.

The old MBrace.Demos repo has a Mersenne prime [example](https://github.com/mbraceproject/MBrace.Demos/blob/master/Demo.Scripts/NonDeterministic/mersenne.fsx) that does nondeterministic searching over exponent ranges. It has a better computation-to-communication ratio so it could be used as a better demonstration for scalability. I'll see if I can incorporate this here during the weekend.

**Comment by dsyme** [comment]
Giving stats on network transfer sizes for each Process would be useful (to allow the user to get a feel for costs).

**Comment by dsyme** [comment]
BTW the CloudStream version was fast, and much simpler `https://github.com/elastacloud/mbrace-on-brisk-starter/pull/12/files#diff-8dae470ce48177d3a1801031d3372313R57`.  Impressive!

**Comment by eiriktsarpalis** [comment]
Good idea, should be relatively easy to measure.

**Pull request merged**
