### PR TITLE
Add nuget package sample

### PR DESCRIPTION
**Pull request by dsyme**
Add a sample that involves getting some nuget packages and using them. The sample inverts 20 random 200x200 matrices on the cluster and checks that the M*M.inverse() is approx. 1.0.

I added this sample because it's useful to remind people that they can go and get any nuget packages they like from within their data scripting code and MBrace arranges for the DLLs to get sent to the cluster.

### CODE REVIEW

**Comment by forki** [comment]
very cool. Looks like:

deploy

**Comment by eiriktsarpalis** [comment]
@forki I'm going to put this gif on the Vagabond front page :laughing: :laughing:

**Comment by dsyme** [comment]
:)

**Comment by isaacabraham** [comment]
Perhaps call Paket.bootstrap.exe rather than tie to a specific Paket version?

**Comment by eiriktsarpalis** [comment]
I think using a type provider package here would make an awesome demo

**Comment by forki** [comment]
http://www.navision-blog.de/blog/2014/10/14/retrieving-github-download-counts/

**Comment by isaacabraham** [comment]
@eiriktsarpalis yeah, something like a CSV parsing and some aggregations would be very effective. Especially compared to some of the other big data frameworks out there that some people are working on...

**Comment by isaacabraham** [comment]
@forki FSPlot looks way better than FSharp.Charting :-)

**Comment by dsyme** [comment]
I don't think Paket.bootstrap.exe has the Paket API inside it.  paket.exe does.  @forki can advise if/when a single stable download point for latest-and-greatest paket.exe exists :)

**Comment by dsyme** [comment]
Re CSV parsing - yes, though we would need to upload data to the table storage, presumably as part of the script.  It make sense for the next samples to all be data-oriented ones.

After that, we really need some more incremental samples, where data is flowing into the system and the system is reporting or emitting results incrementally.  I'd like to understand better how we would architect that with MBrace.Azure.  It's crucial not to concentrate on batch processing alone - even though MBrace is very sweet for that kind of work.

**Comment by eiriktsarpalis** [comment]
@dsyme MBrace does come with support for channels. For example:

``` fsharp
cloud {
    let! sendPort, receivePort = CloudChannel.New<int> ()
    let! _, r = CloudChannel.Send 42 sendPort <||> CloudChannel.Receive receivePort
    return r
}
```

Although I'm not sure of the implementation maturity in the MBrace.Azure version offered by Brisk.

**Comment by isaacabraham** [comment]
@dsyme CSV can just be a regular blob. We could use either the Azure type provider (perhaps not) or Daniel Chambers Azure SDK wrapper to download it, and just pipe it into the FSharp Data. I know that there's an open issue with that to allow parsing of individual rows of data as well rather than a whole document - which would fit well with distributed parsing.

Regarding live reporting etc. - I think the ground work for this is in place, because every process can be queried upon - it's probably a simple matter to build an eventing model over the top of that.

**Comment by isaacabraham** [comment]
@eiriktsarpalis frankly I'm not even sure which version of MBrace.Azure is deployed on Brisk at the moment - that's one of the things I want to sort out next week with you folks :-)

**Comment by forki** [comment]
This should do the trick:

```
if not (File.Exists "paket.exe") then
    let url = "http://fsprojects.github.io/Paket/stable"
    use wc = new Net.WebClient() in let tmp = Path.GetTempFileName() in let stable = wc.DownloadString(url) in wc.DownloadFile(stable, tmp); File.Move(tmp,Path.GetFileName stable)
```

**Comment by forki** [comment]
btw: keep an eye on https://github.com/fsprojects/Paket/issues/677

this might make https://github.com/elastacloud/mbrace-on-brisk-starter/pull/9/files#diff-811695910cf55f79886c9a681cfec76aR45 much easier since the package author would not have to maintain this script.

**Comment by isaacabraham** [comment]
My first thought is great idea - but then as is mentioned this is already available in the power tools - what's going to be offered over and above that? Shouldn't we just use that now?

**Comment by forki** [comment]
yes power tools are similar, but having this integrated in Paket will (hopefully) make tooling much easier. Especially in situations where we don't use VS.

**Pull request merged**
